IPv4/IPv6 and IPv6 only examples for Edge (downstream) clusters
suse-edge/atip pull request #24
Opened 2024-12-18 23:15 UTC by mchiappero

This PR includes examples for single IPv6 and dual-stack single node deployments. Multi-node examples will follow at a later time.

2024-12-19 07:17 UTC, mchiappero commented on telco-examples/edge-clusters/dhcp/dual-stack/single-node/README.md
> +   - `cluster-v4v6-calico_hostlocal.yaml` - the cluster will use Calico as the CNI plugin in combination with "host-local" as Multus IPAM for the second interface
This could be a table.

2024-12-19 07:18 UTC, mchiappero commented on telco-examples/edge-clusters/dhcp-less/dual-stack/single-node/README.md
> + * The network configuration will only apply to the provisioned BMH and not yet on the inspection phase of the host to gather hardware information. This is due to a bug that will force the use of DHC
Need to specify that it only happens when RAs/DHCPs are present.

2024-12-19 08:41 UTC, mchiappero commented
TODO: need to check formatting & references

2024-12-19 09:47 UTC, alknopfler commented
@mchiappero is there a dual-stack or ipv6 multi-node example? maybe I'm wrong but I've only seen the single nodes.

2024-12-19 11:12 UTC, alknopfler requested changes
Thanks Marco for this feature!!! Some comments and change requested

2024-12-19 11:12 UTC, alknopfler commented on telco-examples/edge-clusters/dhcp/ipv6/single-node/README.md
> +This directory contains some sample CAPI manifest files that enable the creation of Edge clusters where the bare metal hosts, and the executing containers on top, are exclusively connected through IP
```suggestion
This directory contains examples of BMH and CAPI manifest files that allow the creation of Edge clusters with support for IPv6, with the following characteristics:
```

2024-12-19 11:12 UTC, alknopfler commented on telco-examples/edge-clusters/dhcp/ipv6/single-node/README.md
> + * The network configuration will only apply to the provisioned BMH and not yet on the inspection phase of the host to gather hardware information. This is due to a bug that will force the use of RA/
```suggestion
 * The network configuration will only apply to the provisioned BMH and not yet on the inspection phase of the host to gather hardware information. This is due to a bug that will force the use of RA/DHCP with the default settings; a resolution is espected coming soon.
```

2024-12-19 11:12 UTC, alknopfler commented on telco-examples/edge-clusters/dhcp/ipv6/single-node/README.md
> +- `single-cni`:
Same comment about renaming to keep them with similar format

2024-12-19 11:12 UTC, alknopfler commented on telco-examples/edge-clusters/dhcp/ipv6/single-node/README.md
> +- `RKE2ControlPlane.spec.agentConfig.nodeName` - the hostname that will be set on the host
as I said, we don't need to modify this

2024-12-19 19:22 UTC, alknopfler commented
one more comment, in DHCP you've added the network custom script, but at least for ipv4 is not needed. Is it something new for ipv6 / dual stack?

2024-12-20 09:35 UTC, mchiappero commented on telco-examples/edge-clusters/dhcp/dual-stack/single-node/README.md
> +   - `cluster-v4v6-calico_hostlocal.yaml` - the cluster will use Calico as the CNI plugin in combination with "host-local" as Multus IPAM for the second interface
Yes, I thought of that, and I will do it, but honestly I don't see the value in having the "Telco" prefix in a ATIP, that is telco specific, repo. Also, some example are not necessarily telco specific in the end. I think it's clearer to have filenames based on the roles (as they are all "CAPI" anyway) BMH & Cluster. What do you think? We can align them for now and change them afterward?

2024-12-20 09:36 UTC, mchiappero commented on telco-examples/edge-clusters/dhcp-less/dual-stack/single-node/README.md
> + * The network configuration will only apply to the provisioned BMH and not yet on the inspection phase of the host to gather hardware information. This is due to a bug that will force the use of DHC
Done

2024-12-20 09:37 UTC, mchiappero commented
> @mchiappero is there a dual-stack or ipv6 multi-node example? maybe I'm wrong but I've only seen the single nodes. [EDIT] After talking about it directly, let's explain it in the README to say that ipv6 examples for multimode are prepared and they're in QA phase. Thanks Marco

Good point, let me do it.

2024-12-20 09:44 UTC, mchiappero commented
> one more comment, in DHCP you've added the network custom script, but at least for ipv4 is not needed. Is it something new for ipv6 / dual stack?

Yes, it's explained in the commit message (I would not squash).

2024-12-20 11:04 UTC, mchiappero commented on telco-examples/edge-clusters/dhcp-less/dual-stack/single-node/README.md
> +This directory contains some sample CAPI manifest files that enable the creation of Edge clusters where the bare metal hosts, and the executing containers on top, are connected through both IPv4 and
I'm not sure on this one, I want to be clear on dual stack being available on both the host and the k8s cluster. You could potentially have a dual-stack host but a v4 only cluster and, maybe the other way around too.

2024-12-20 11:06 UTC, mchiappero commented on telco-examples/edge-clusters/dhcp-less/dual-stack/single-node/README.md
> + * The network configuration will only apply to the provisioned BMH and not yet on the inspection phase of the host to gather hardware information. This is due to a bug that will force the use of DHC
True, but right now we don't have a github issue.

2024-12-20 11:10 UTC, mchiappero commented on telco-examples/edge-clusters/dhcp-less/ipv6/single-node/README.md
> +Once the required BMH file has been selected and refined, in order for it to work, it must also be filled with some values common to all the BMH definitions in addition to the network specific ones p
If you mean to copy and paste, I think it's just too messy and too much work.

2024-12-20 11:35 UTC, mchiappero commented on telco-examples/edge-clusters/README.md
> +
I think I will create a table here.

2024-12-20 13:19 UTC, alknopfler commented on telco-examples/edge-clusters/dhcp-less/ipv6/single-node/README.md
> +Once the required BMH file has been selected and refined, in order for it to work, it must also be filled with some values common to all the BMH definitions in addition to the network specific ones p
Yes I don't know why I added the comment on this one, sorry

2024-12-20 13:58 UTC, mchiappero commented on telco-examples/edge-clusters/dhcp/dual-stack/single-node/README.md
> +   - `cluster-v4v6-calico_hostlocal.yaml` - the cluster will use Calico as the CNI plugin in combination with "host-local" as Multus IPAM for the second interface
Okay, will do that.

2024-12-20 17:26 UTC, mchiappero commented
I think we can merge now.

2024-12-20 19:25 UTC, alknopfler reviewed
a pair of comments just to double check please...
Anyway lgtm keeping in mind we need to refactor the folder structure as we decided

2024-12-20 19:25 UTC, alknopfler commented on telco-examples/edge-clusters/README.md
> +
yeah now makes sense

2024-12-20 19:25 UTC, alknopfler commented on telco-examples/edge-clusters/README.md
> +For all the examples, there are 2 options available to be used depending on your environment:
IMHO with the previous table should be enough now, but let's keep as is because we should refactor the folder structure soon

2024-12-20 19:25 UTC, alknopfler commented on telco-examples/edge-clusters/dhcp/dual-stack/single-node/README.md
> +- `bmh-example_v4dhcp-v6dhcp+route.yaml` - use in environments where Router Advertisements (RAs) are not enabled in the network (or should not be used) and IPv6 should only rely on DHCP for the addre
Did you check this one?

2024-12-20 19:25 UTC, alknopfler commented on telco-examples/edge-clusters/dhcp/dual-stack/single-node/README.md
> +        - `${CONTROLPLANE_INTERFACE}` - the name of the interface to be used for the egressing traffic matching the default route
Did you check this one?

2024-12-21 07:42 UTC, alknopfler approved these changes

2025-01-08 13:28 UTC, merged